spring:
  application:
    name: Cards-Dictionary-App

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


  datasource:
    url: jdbc:postgresql://cards-cards-dictionary.c.aivencloud.com:12753/defaultdb
    username: avnadmin
    password: ${AIVEN_PASS}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true